"""
Build a single audit_bundle.md containing every piece of the NFL Draft
Predictor so an external reviewer has complete context:

- All Python source (models, features, data pipelines, API)
- All frontend source (TSX pages, components, lib)
- Config (requirements.txt, render.yaml, Dockerfile, package.json, vite.config)
- Data schema + representative samples (teams, prospects, trades, agents)
- Run/deploy docs (DEPLOY.md)

Writes to ./AUDIT_BUNDLE.md
"""
import json
import os
from pathlib import Path

ROOT = Path(__file__).parent
OUT = ROOT / "AUDIT_BUNDLE.md"

def lang_for(path: Path) -> str:
    ext = path.suffix.lower()
    return {
        ".py": "python", ".ts": "ts", ".tsx": "tsx", ".js": "js",
        ".json": "json", ".css": "css", ".html": "html",
        ".yml": "yaml", ".yaml": "yaml", ".md": "markdown",
        ".sh": "bash", ".cfg": "ini", ".toml": "toml",
    }.get(ext, "")

def emit_file(fh, label: str, path: Path, max_bytes=None):
    if not path.exists():
        fh.write(f"\n\n### {label} — MISSING: `{path}`\n")
        return
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        fh.write(f"\n\n### {label} — READ ERROR: {e}\n")
        return
    truncated = ""
    if max_bytes and len(text) > max_bytes:
        text = text[:max_bytes]
        truncated = f"\n\n[... truncated at {max_bytes} bytes ...]"
    lang = lang_for(path)
    rel = path.relative_to(ROOT)
    fh.write(f"\n\n### {label}\n`{rel}` ({len(text)} chars)\n\n```{lang}\n{text}{truncated}\n```\n")

def emit_section(fh, title: str, note: str = ""):
    fh.write(f"\n\n---\n\n## {title}\n")
    if note:
        fh.write(f"\n{note}\n")

def emit_json_sample(fh, label: str, path: Path, max_items=3, max_chars=6000):
    """Emit first N items of a JSON file (dict keys or list entries) for schema inspection."""
    if not path.exists():
        fh.write(f"\n\n### {label} — MISSING: `{path}`\n"); return
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        fh.write(f"\n\n### {label} — JSON PARSE ERROR: {e}\n"); return
    rel = path.relative_to(ROOT)
    fh.write(f"\n\n### {label}\n`{rel}`\n\n")
    if isinstance(data, dict):
        fh.write(f"- type: dict, top-level keys: {len(data)}\n")
        keys = list(data.keys())
        fh.write(f"- first keys: {keys[:10]}\n\n")
        sample = {k: data[k] for k in keys[:max_items]}
        txt = json.dumps(sample, indent=2, default=str)[:max_chars]
        fh.write(f"```json\n{txt}\n```\n")
    elif isinstance(data, list):
        fh.write(f"- type: list, length: {len(data)}\n\n")
        txt = json.dumps(data[:max_items], indent=2, default=str)[:max_chars]
        fh.write(f"```json\n{txt}\n```\n")

def emit_csv_sample(fh, label: str, path: Path, head=8):
    if not path.exists():
        fh.write(f"\n\n### {label} — MISSING: `{path}`\n"); return
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    rel = path.relative_to(ROOT)
    fh.write(f"\n\n### {label}\n`{rel}` ({len(lines)} rows incl. header)\n\n")
    sample = "\n".join(lines[:head])
    fh.write(f"```\n{sample}\n```\n")

# ---------------------- Build the bundle ----------------------
with OUT.open("w", encoding="utf-8") as fh:
    fh.write("# NFL Draft Predictor 2026 — Full Audit Bundle\n\n")
    fh.write("Single-file dump of every meaningful source, schema, and data sample.\n")
    fh.write("Generated by build_audit_bundle.py. Intended for external AI review.\n")

    # ---- 1. README / Deploy / Top-level config
    emit_section(fh, "1. Top-level docs and config")
    for p in [
        ROOT / "README.md",
        ROOT / "DEPLOY.md",
        ROOT / "requirements.txt",
        ROOT / "render.yaml",
        ROOT / "Dockerfile",
        ROOT / "run_dashboard.py",
    ]:
        emit_file(fh, p.name, p)

    # ---- 2. Stage 1 (per-position ensembles)
    emit_section(fh, "2. Stage 1 — per-position draft-pick regressors",
                 "Trains DEF/OL/QB/SKILL ensembles on historical draft data. "
                 "Input = X_<POS>_historical.csv, target = y_<POS>_historical.csv. "
                 "Outputs saved to models/*_ensemble.pkl.")
    for p in [
        ROOT / "src/features/build_feature_matrix.py",
        ROOT / "src/models/train_stage1.py",
        ROOT / "src/models/backtest.py",
        ROOT / "src/models/ablation.py",
        ROOT / "src/models/predict_2026.py",
    ]:
        emit_file(fh, p.name, p)

    # ---- 3. Stage 2 core (game-theoretic team-agent sim) — THE BIG ONE
    emit_section(fh, "3. Stage 2 — game-theoretic team-agent simulator",
                 "Core model. Each team is an autonomous agent with needs, "
                 "coaching priors, cap context, analyst-bias noise, trade logic. "
                 "Monte-Carlo over N runs → produces predictions_2026.csv and "
                 "monte_carlo_2026_v12.csv.")
    emit_file(fh, "stage2_game_theoretic.py (CORE — 2708 lines)",
              ROOT / "src/models/stage2_game_theoretic.py")
    emit_file(fh, "stage2_team_picks.py (alt/older team-pick logic)",
              ROOT / "src/models/stage2_team_picks.py")

    # ---- 4. Data pipeline scripts
    emit_section(fh, "4. Data pipeline (src/data/)",
                 "Ingest → enrich → build feature jsons/CSVs consumed by the "
                 "Stage 2 sim. Listed roughly in execution order.")
    data_order = [
        # scraping / fetching raw
        "fetch_2026_prospects.py",
        "fetch_2026_combine.py",
        "fetch_2026_ages.py",
        "fetch_2026_draft_order.py",
        "fetch_2026_team_needs.py",
        "scrape_historical_drafts.py",
        "scrape_combine_data.py",
        "scrape_college_stats.py",
        "scrape_r1_trades.py",
        "fetch_college_stats_api.py",
        "clean_college_stats.py",
        "inspect_pfr_headers.py",
        # parsing / PDFs / PFF
        "parse_team_profiles_pdf.py",
        "parse_pff_excel.py",
        # enrichment
        "fix_data_integrity.py",
        "enrich_all_features.py",
        "add_chatgpt_features.py",
        "add_final_enrichment.py",
        "add_positional_value.py",
        "add_sackseer_analyst_biases.py",
        # context
        "build_cap_and_coaching.py",
        "compute_roster_context.py",
        "compute_gm_allocation.py",
        "enhance_team_context.py",
        "compute_empirical_trade_rates.py",
        # live intel + team agents
        "ingest_analyst_mocks.py",
        "aggregate_live_intel.py",
        "daily_intel_update.py",
        "build_team_agents.py",
    ]
    for name in data_order:
        emit_file(fh, name, ROOT / "src/data" / name)

    # ---- 5. API
    emit_section(fh, "5. FastAPI / Flask API (src/api/app.py)",
                 "HTTP endpoints that the frontend calls: /prospects, /teams, "
                 "/simulate, /simulate/replay, etc. Hosts model inference.")
    emit_file(fh, "app.py", ROOT / "src/api/app.py")

    # ---- 6. Frontend
    emit_section(fh, "6. Frontend (React + Vite + Tailwind)")
    frontend_files = [
        "frontend/package.json",
        "frontend/vite.config.ts",
        "frontend/tailwind.config.js",
        "frontend/postcss.config.js",
        "frontend/tsconfig.json",
        "frontend/tsconfig.app.json",
        "frontend/tsconfig.node.json",
        "frontend/index.html",
        "frontend/eslint.config.js",
        "frontend/src/main.tsx",
        "frontend/src/App.tsx",
        "frontend/src/index.css",
        "frontend/src/lib/api.ts",
        "frontend/src/lib/format.ts",
        "frontend/src/lib/teams.ts",
        "frontend/src/components/AboutModal.tsx",
        "frontend/src/components/Tooltip.tsx",
        "frontend/src/pages/Dashboard.tsx",
        "frontend/src/pages/BuildMock.tsx",
        "frontend/src/pages/Prospects.tsx",
        "frontend/src/pages/TeamDetail.tsx",
        "frontend/src/pages/League.tsx",
        "frontend/src/pages/Simulate.tsx",
        "frontend/src/pages/Settings.tsx",
    ]
    for rel in frontend_files:
        emit_file(fh, os.path.basename(rel), ROOT / rel)

    # ---- 7. Data — feature JSONs (schemas + samples)
    emit_section(fh, "7. Feature JSONs (schemas + first entries)",
                 "These feed Stage 2 directly. Showing shape + first ~3 entries.")
    for rel in [
        "data/features/team_agents_2026.json",
        "data/features/analyst_aggregate_2026.json",
        "data/features/analyst_consensus_2026.json",
        "data/features/cap_context_2026.json",
        "data/features/coaching_tree_2026.json",
        "data/features/roster_context_2026.json",
        "data/features/team_profiles_narrative_2026.json",
        "data/features/trade_empirical_2021_2025.json",
        "data/features/trade_scenarios_expanded_2026.json",
    ]:
        emit_json_sample(fh, os.path.basename(rel), ROOT / rel)

    # ---- 8. Model outputs / processed CSVs (head samples)
    emit_section(fh, "8. Processed model outputs + inputs (CSV heads)")
    for rel in [
        "data/processed/predictions_2026.csv",
        "data/processed/monte_carlo_2026_v12.csv",
        "data/processed/prospects_2026.csv",
        "data/processed/prospects_2026_enriched.csv",
        "data/processed/team_context_2026.csv",
        "data/processed/team_context_2026_enriched.csv",
        "data/processed/team_needs_2026.csv",
        "data/processed/gm_positional_allocation.csv",
        "data/processed/picks_with_needs_2026.csv",
        "data/processed/prospects_with_demand.csv",
        "data/processed/stage2_mock_draft.csv",
        "data/processed/stage2_team_picks.csv",
    ]:
        emit_csv_sample(fh, os.path.basename(rel), ROOT / rel, head=10)

    emit_json_sample(fh, "model_reasoning_2026.json",
                     ROOT / "data/processed/model_reasoning_2026.json",
                     max_items=2, max_chars=8000)
    emit_json_sample(fh, "monte_carlo_trades_2026.json",
                     ROOT / "data/processed/monte_carlo_trades_2026.json",
                     max_items=3, max_chars=5000)

    # ---- 9. Historical training data heads
    emit_section(fh, "9. Stage 1 historical training data (heads)")
    for pos in ["DEF", "OL", "QB", "SKILL"]:
        emit_csv_sample(fh, f"X_{pos}_historical.csv",
                        ROOT / f"data/features/X_{pos}_historical.csv", head=6)
        emit_csv_sample(fh, f"y_{pos}_historical.csv",
                        ROOT / f"data/features/y_{pos}_historical.csv", head=6)
        emit_csv_sample(fh, f"meta_{pos}_historical.csv",
                        ROOT / f"data/features/meta_{pos}_historical.csv", head=6)

    # ---- 10. Live intel (news / betting / visits)
    emit_section(fh, "10. Live intel snapshots (as of 2026-04-17)")
    for rel in [
        "data/live/master_intel_latest.json",
        "data/live/betting_odds_cbs_2026-04-17.json",
        "data/live/betting_odds_vegasinsider_2026-04-17.json",
        "data/live/stock_moves_twsn_2026-04-17.json",
        "data/live/visits_nfltr_2026-04-17.json",
        "data/live/visits_pfn_2026-04-17.json",
        "data/live/visits_walterfootball_2026-04-17.json",
    ]:
        emit_json_sample(fh, os.path.basename(rel), ROOT / rel, max_items=5, max_chars=5000)

    # ---- 11. Raw inputs (context-heavy markdown only — no HTML blobs)
    emit_section(fh, "11. Raw research notes and patterns")
    for rel in [
        "data/raw/draft_patterns_2020_2025.md",
        "data/raw/trade_reason_taxonomy_2020_2025.md",
        "data/raw/draft_week_news_2026-04-18.md",
        "data/raw/prospect_audit_2026.md",
    ]:
        emit_file(fh, os.path.basename(rel), ROOT / rel)
    # team profiles txt is huge; include it
    emit_file(fh, "2026_NFL_Draft_Team_Profiles.txt (large)",
              ROOT / "data/2026_NFL_Draft_Team_Profiles.txt")

    # ---- 12. Stage 1 model summary outputs
    emit_section(fh, "12. Stage 1 training/shap outputs")
    emit_csv_sample(fh, "_stage1_results.csv", ROOT / "models/_stage1_results.csv", head=30)
    emit_csv_sample(fh, "_stage1_shap.csv",    ROOT / "models/_stage1_shap.csv",    head=60)

    fh.write("\n\n---\n\n_End of bundle._\n")

size = OUT.stat().st_size
print(f"Wrote {OUT} ({size/1024:.1f} KB)")
